@startuml
class GuessTheNumber {
  - targetNumber: int
  - maxGuesses: int
  - currentGuessesLeft: int
  - numberRange: int
  
  + playGame(): boolean
  - getRange(): int
  - getMaxGuesses(range: int): int
  - generateTargetNumber(range: int): void
  - getPlayerGuess(): int
  - evaluateGuess(guess: int): boolean
  - declareRoundResult(isCorrect: boolean): void
}
@enduml
