name: Generate PlantUML

on: push

permissions:
  contents: write

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate PlantUML Diagrams
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: diagrams
          message: "Render PlantUML diagrams"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
